// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpm7xXMvynzG8PLbUX74i7lP4nRx5FRU',
    appId: '1:188949770758:web:1fd3abaadbebc506980987',
    messagingSenderId: '188949770758',
    projectId: 'avoid-it-d4b8c',
    authDomain: 'avoid-it-d4b8c.firebaseapp.com',
    storageBucket: 'avoid-it-d4b8c.appspot.com',
    measurementId: 'G-KSBR6QMQDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2C0Ia6JLGZRPjqM2iCLmAcoxOYsSPKo',
    appId: '1:188949770758:android:7cf83d5b7791080b980987',
    messagingSenderId: '188949770758',
    projectId: 'avoid-it-d4b8c',
    storageBucket: 'avoid-it-d4b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9snwBvxbAHkr9bWsbQo3mI3f0AcuGHFc',
    appId: '1:188949770758:ios:48b22804903d7e3b980987',
    messagingSenderId: '188949770758',
    projectId: 'avoid-it-d4b8c',
    storageBucket: 'avoid-it-d4b8c.appspot.com',
    iosClientId: '188949770758-9i11a5g2n20g7tikljc5sr5gj5mvinhd.apps.googleusercontent.com',
    iosBundleId: 'com.beast.avoidit',
  );
}
